import Foundation

/// A searchable emoji set for the project picker — Slack-style: type a word, get matches. Not
/// exhaustive (that's what ⌃⌘Space is for); a curated set weighted toward dev/project labels
/// plus common expressive emoji. Each line is "emoji keyword keyword …".
enum EmojiCatalog {
    struct Entry { let emoji: String; let keywords: [String] }

    static let all: [Entry] = raw.compactMap { line in
        let parts = line.split(separator: " ").map(String.init)
        guard let first = parts.first else { return nil }
        return Entry(emoji: first, keywords: Array(parts.dropFirst()))
    }

    /// Emoji whose keywords match `query` — prefix matches ranked before substring matches.
    /// Empty query returns the whole set (browsable).
    static func search(_ query: String) -> [String] {
        let q = query.lowercased().trimmingCharacters(in: .whitespaces)
        guard !q.isEmpty else { return all.map(\.emoji) }
        var prefix: [String] = [], substring: [String] = []
        for e in all {
            if e.keywords.contains(where: { $0.hasPrefix(q) }) { prefix.append(e.emoji) }
            else if e.keywords.contains(where: { $0.contains(q) }) { substring.append(e.emoji) }
        }
        return prefix + substring
    }

    private static let raw: [String] = [
        // Dev / project
        "🚀 rocket launch ship startup deploy fast",
        "🔥 fire flame hot lit burn",
        "⚡ zap lightning bolt fast power energy",
        "🐛 bug insect defect issue",
        "🔧 wrench tool fix config",
        "🛠️ tools hammer wrench build fix",
        "⚙️ gear settings config cog options",
        "🔨 hammer build tool",
        "🧪 test tube science experiment lab",
        "🔬 microscope science research",
        "💻 laptop computer code dev",
        "🖥️ desktop computer monitor",
        "📱 phone mobile app smartphone",
        "🤖 robot bot ai automation",
        "🧠 brain smart mind ai think",
        "💡 idea bulb light tip",
        "🔑 key auth login secret",
        "🔒 lock secure closed private",
        "🔓 unlock open",
        "🛡️ shield security protect defense",
        "📦 package box module dependency parcel",
        "🗂️ files folders organize tabs",
        "🗄️ database cabinet storage archive",
        "📊 chart bar stats analytics graph",
        "📈 growth trending up chart increase",
        "📉 chart down decrease loss",
        "🎯 target goal aim bullseye focus",
        "🧩 puzzle piece module plugin",
        "🪝 hook fishing",
        "🧵 thread sew string",
        "🔌 plug electric power connect api",
        "🛰️ satellite space signal",
        "🌐 web globe internet world network",
        "🔗 link chain url connect",
        "⏱️ timer stopwatch time perf speed",
        "🧰 toolbox tools kit",
        "🔍 search find magnify look zoom",
        "📝 note memo edit write doc",
        "✅ check done complete ok yes success green",
        "❌ x cross wrong no fail error red",
        "⭐ star favorite",
        "✨ sparkles shiny magic new clean",
        "🏗️ build construction crane wip",
        "🚧 wip construction barrier progress",
        "🧱 brick wall block",
        "🪄 magic wand spell",
        "⚗️ alembic chemistry science",
        "🧬 dna genetics bio",
        "🦠 microbe germ virus bug",
        "📡 antenna satellite signal broadcast",
        "🕹️ joystick game control",
        "🎮 game controller gaming play",
        "🧮 abacus math calc count",
        "📐 ruler triangle measure geometry",
        "📏 ruler measure straight",
        "🖊️ pen write ink",
        "✏️ pencil write edit draw",
        "🖍️ crayon color draw",
        "🎨 art palette paint design color",
        "🧭 compass direction navigate",
        "🗺️ map location travel",
        "📌 pin pushpin location mark",
        "📍 location pin place marker",
        "🏷️ label tag price name",
        "🔖 bookmark tag save",
        "📎 paperclip attach clip",
        "✂️ scissors cut",
        "🗑️ trash bin delete remove garbage",
        "💾 save floppy disk store",
        "🧯 extinguisher fire safety",
        "🚨 siren alert emergency alarm",
        "⚠️ warning caution alert danger",
        "🆘 sos help emergency",
        "💯 hundred perfect score full",
        "🔔 bell notification alert ring",
        "📣 megaphone announce shout promote",
        "💬 speech bubble comment chat message talk",
        "💭 thought bubble think idea",
        "📚 books library docs read",
        "📖 book open read docs manual",
        "🧾 receipt bill invoice",
        "💰 money bag cash rich fund",
        "💳 credit card payment pay",
        "💎 gem diamond jewel valuable",
        "🪙 coin money token",
        "🛒 cart shopping buy ecommerce",
        "🎫 ticket admission event",
        "🔮 crystal ball future predict magic",
        // Faces
        "😀 grin happy smile",
        "😁 grin beam smile",
        "😂 joy laugh cry tears funny lol",
        "🤣 rofl rolling laugh funny",
        "😊 smile blush happy",
        "😇 angel innocent halo",
        "🙂 slight smile",
        "😉 wink",
        "😍 heart eyes love adore",
        "🥰 love hearts adore",
        "😘 kiss blow",
        "😜 tongue wink playful",
        "🤪 zany silly crazy",
        "🤗 hug hands",
        "🤔 thinking hmm consider",
        "🤨 raised eyebrow skeptical suspicious",
        "😐 neutral meh",
        "🙄 eye roll annoyed",
        "😏 smirk sly",
        "😴 sleep zzz tired",
        "😪 sleepy tired",
        "🥱 yawn bored tired",
        "😅 sweat nervous relief phew",
        "😭 sob cry sad tears",
        "😢 cry sad tear",
        "😤 huff frustrated steam",
        "😠 angry mad",
        "😡 rage furious mad red",
        "🤯 mind blown shock explode",
        "😱 scream shock fear",
        "😳 flushed embarrassed surprise",
        "🥺 pleading puppy eyes cute beg",
        "😎 cool sunglasses awesome",
        "🤓 nerd geek glasses",
        "🧐 monocle inspect examine",
        "🥳 party celebrate hat",
        "😈 devil evil grin",
        "🤡 clown joker",
        "💩 poop crap",
        "👻 ghost boo spooky",
        "💀 skull dead death",
        "☠️ skull crossbones danger poison",
        "👽 alien ufo space",
        "🎃 pumpkin halloween",
        // Gestures
        "👍 thumbs up like approve yes good",
        "👎 thumbs down dislike no bad",
        "👏 clap applause bravo",
        "🙌 raise hands praise celebrate",
        "🙏 pray thanks please hope namaste",
        "💪 muscle strong flex power",
        "🤝 handshake deal agree partner",
        "✊ fist power solidarity",
        "👊 fist bump punch",
        "✌️ peace victory",
        "🤞 fingers crossed luck hope",
        "🤟 love you rock",
        "🤘 rock horns metal",
        "👌 ok perfect good",
        "👀 eyes look watch see",
        "🫡 salute respect yes sir",
        "👋 wave hi hello bye",
        // Animals
        "🐶 dog puppy pet",
        "🐱 cat kitten pet meow",
        "🦊 fox",
        "🐻 bear",
        "🐼 panda",
        "🐨 koala",
        "🐯 tiger",
        "🦁 lion",
        "🐸 frog",
        "🐵 monkey",
        "🐧 penguin",
        "🦉 owl",
        "🦅 eagle bird",
        "🐝 bee honey buzz",
        "🦋 butterfly",
        "🐢 turtle slow",
        "🐍 snake",
        "🦖 dinosaur trex rawr",
        "🦕 dinosaur sauropod",
        "🐙 octopus",
        "🦀 crab",
        "🐳 whale",
        "🐬 dolphin",
        "🦈 shark",
        "🦄 unicorn magic rare",
        "🐔 chicken",
        "🐤 chick baby bird",
        "🦜 parrot bird",
        "🐴 horse",
        "🐮 cow",
        "🐷 pig",
        "🐰 rabbit bunny",
        "🐭 mouse",
        "🐹 hamster",
        // Plants / nature
        "🌵 cactus desert plant",
        "🌲 evergreen tree pine forest",
        "🌳 tree forest",
        "🌴 palm tree tropical beach",
        "🌱 seedling sprout grow plant new",
        "🍀 clover luck four leaf",
        "🍁 maple leaf autumn fall",
        "🍄 mushroom fungus",
        "🌸 blossom cherry flower spring pink",
        "🌷 tulip flower",
        "🌹 rose flower love",
        "🌻 sunflower flower",
        "🌼 daisy flower",
        "💐 bouquet flowers",
        "🌊 wave ocean sea water",
        "💧 droplet water drop",
        "🔆 bright sun light",
        "☀️ sun sunny weather clear",
        "🌙 moon crescent night",
        "⭐ star night",
        "🌟 glowing star shine",
        "🌈 rainbow color pride",
        "☁️ cloud weather",
        "⛅ partly cloudy weather sun",
        "❄️ snowflake snow cold winter",
        "🌪️ tornado storm cyclone",
        "🌋 volcano eruption",
        "⛰️ mountain peak",
        "🏔️ snow mountain peak",
        // Food & drink
        "🍎 apple fruit red",
        "🍊 orange fruit tangerine",
        "🍋 lemon fruit sour citrus",
        "🍌 banana fruit",
        "🍉 watermelon fruit summer",
        "🍇 grapes fruit wine",
        "🍓 strawberry fruit berry",
        "🍑 peach fruit",
        "🥝 kiwi fruit",
        "🥑 avocado",
        "🌶️ pepper hot spicy chili",
        "🌽 corn maize",
        "🥕 carrot vegetable",
        "🍔 burger hamburger fast food",
        "🍟 fries chips fast food",
        "🍕 pizza slice",
        "🌮 taco mexican",
        "🍣 sushi japanese fish",
        "🍜 ramen noodle soup",
        "🍩 donut doughnut sweet",
        "🍪 cookie sweet",
        "🍰 cake slice dessert sweet",
        "🎂 birthday cake celebrate",
        "🍫 chocolate sweet",
        "🍿 popcorn movie snack",
        "☕ coffee tea hot cup caffeine",
        "🍵 tea green matcha",
        "🥤 soda cup drink",
        "🧋 boba bubble tea milk",
        "🍺 beer drink cheers",
        "🍻 beers cheers drink toast",
        "🍷 wine drink glass",
        "🥂 champagne cheers celebrate toast",
        "🍸 cocktail drink martini",
        // Activities / objects
        "⚽ soccer football ball sport",
        "🏀 basketball ball sport",
        "🏈 football american sport",
        "⚾ baseball ball sport",
        "🎾 tennis ball sport",
        "🏆 trophy win award champion first",
        "🥇 gold medal first win",
        "🥈 silver medal second",
        "🥉 bronze medal third",
        "🎖️ medal military honor",
        "🎬 movie clapper film cut action",
        "🎤 mic sing karaoke voice",
        "🎧 headphones music audio listen",
        "🎵 music note song",
        "🎸 guitar music rock",
        "🥁 drum music beat",
        "🎹 piano keyboard music",
        "🎲 dice random game luck",
        "🎳 bowling",
        "🧩 jigsaw puzzle piece",
        "🎁 gift present box wrapped",
        "🎈 balloon party",
        "🎉 party tada celebrate confetti congrats",
        "🎊 confetti party celebrate",
        "🪄 wand magic",
        "🕯️ candle light",
        "🧨 firecracker explosive",
        "💣 bomb explosive danger",
        "🔫 gun weapon water pistol",
        "🗝️ key old antique",
        "🎀 ribbon bow gift",
        // Travel / places
        "🚗 car auto vehicle drive",
        "🏎️ race car fast speed",
        "🚕 taxi cab",
        "🚌 bus",
        "🚑 ambulance emergency",
        "🚚 truck delivery",
        "🚲 bike bicycle cycle",
        "🏍️ motorcycle bike",
        "✈️ airplane plane fly travel flight",
        "🚀 rocketship space",
        "🛸 ufo alien flying saucer",
        "🚁 helicopter chopper",
        "⛵ sailboat boat sea",
        "🚢 ship cruise boat sea",
        "⚓ anchor boat marine",
        "🏠 house home building",
        "🏡 house home garden",
        "🏢 office building work company",
        "🏭 factory industry",
        "🏰 castle fortress",
        "🗽 statue liberty landmark",
        "🏝️ island beach tropical vacation",
        "🏖️ beach vacation sand",
        "⛺ tent camping outdoor",
        "🌃 night city stars",
        "🏙️ cityscape city skyline urban",
        "🌉 bridge night",
        "🎆 fireworks celebrate night",
        // Symbols / hearts
        "❤️ heart love red like",
        "🧡 orange heart love",
        "💛 yellow heart love",
        "💚 green heart love",
        "💙 blue heart love",
        "💜 purple heart love",
        "🖤 black heart love dark",
        "🤍 white heart love",
        "💔 broken heart sad breakup",
        "💕 hearts love two",
        "💖 sparkling heart love shine",
        "☮️ peace sign",
        "☯️ yin yang balance",
        "♻️ recycle reuse green eco",
        "🔱 trident emblem",
        "⚜️ fleur de lis emblem",
        "🚩 flag red mark milestone",
        "🏁 checkered flag finish race done",
        "🏴‍☠️ pirate flag skull jolly roger",
        "🏳️‍🌈 rainbow pride flag lgbt",
        "🔴 red circle dot",
        "🟠 orange circle dot",
        "🟡 yellow circle dot",
        "🟢 green circle dot go",
        "🔵 blue circle dot",
        "🟣 purple circle dot",
        "⚫ black circle dot",
        "⚪ white circle dot",
        "🟥 red square",
        "🟩 green square",
        "🟦 blue square",
        "🟨 yellow square",
        "⬛ black square",
        "⬜ white square",
        "▶️ play start",
        "⏸️ pause",
        "⏹️ stop",
        "🔁 repeat loop",
        "🔀 shuffle random",
        "🔄 refresh sync reload cycle",
        "➕ plus add new",
        "➖ minus remove subtract",
        "♾️ infinity endless loop",
        "❓ question help unknown",
        "❗ exclamation important alert",
        "💤 zzz sleep tired",
        "💥 boom explosion collision impact",
        "🌀 cyclone spiral loading",
        "🆕 new badge",
        "🆓 free badge",
        "🔝 top up best",
    ]
}
